[platformio]
src_dir = .

[env:m5stack-cardputer]
platform = espressif32 @ ^6.7.0
board = m5stack-cardputer
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<main.cpp>
    +<lib/ESP8266Audio/src/*.cpp>
    +<lib/ESP8266Audio/src/libflac/*.c>
    +<lib/ESP8266Audio/src/libflac/*.cpp>
    +<lib/ESP8266Audio/src/libhelix-aac/*.c>
    +<lib/ESP8266Audio/src/libhelix-aac/*.cpp>
    +<lib/ESP8266Audio/src/libhelix-mp3/*.c>
    +<lib/ESP8266Audio/src/libhelix-mp3/*.cpp>
    +<lib/ESP8266Audio/src/libmad/*.c>
    +<lib/ESP8266Audio/src/libmad/*.cpp>
lib_extra_dirs =
    c:/Users/silas/OneDrive/Aplicativos/m5-stack/Cardputer ADV/.pio/libdeps/m5stack-cardputer
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -Os
    -DBOARD_HAS_PSRAM
    -Ilib/ESP8266Audio/src
